pipeline:
  name: Categories
  identifier: Categories
  projectIdentifier: API
  orgIdentifier: CCRA
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Categories
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.CTAcluster
              namespace: harness-dmi-sandbox
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:18-alpine
                    shell: Sh
                    command: npm install
