apiVersion: v1
appVersion: "1.0"
description: A Helm chart for DG Kubernetes Meetup
name: neverland-ms-products
version: 0.0.2
sources:
  - https://bitbucket.org/devgurus/neverland-ms-products
keywords:
  - microservice
  - meetup
  - dashboard
maintainers:
  - name: Lean Soler
    email: lean@devgurus.io
  - name: Agustin Romano
    email: agus@devgurus.io

