{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fastify-microservice-template.fullname" . }}
  labels:
    app: {{ template "fastify-microservice-template.name" . }}
    chart: {{ template "fastify-microservice-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  commercetools.client.secret: {{ .Values.commercetools.client.secret | b64enc }}
{{- end -}}