apiVersion: v1
kind: Secret
metadata:
  name: {{ template "neverland-ms-products.name" . }}
  labels:
    app: {{ template "neverland-ms-products.name" . }}
    chart: {{ template "neverland-ms-products.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  commercetools_clientId: {{ .Values.commercetools_clientId | b64enc }}
  commercetools_clientSecret: {{ .Values.commercetools_clientSecret | b64enc }}
