# Override the Chart name, used as suffix (Release-chart)
#nameOverride: "your-ms"

# Override the endpoint
# relativePathOverride: "test"
# versionOverride: "v1"

resources:
  limits:
    cpu: 1
    memory: 1536Mi
  requests:
    cpu: 0m
    memory: 256Mi

image:
  repository: registry.gitlab.com/devgurus/commercetools-accelerator/development/api/categories
  tag: latest
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  # TODO request at 80% targetCPUUtilizationPercentage: 50

istio:
  gateways:
    - ct-acc-tls-istio-gateway
  corsPolicy:
    allowOrigins:
      - regex: '.'

secret:
  enabled: true
  env: {}
  CT_CLIENT_SECRET: 'dummy-scret'

jwt:
  policyEnabled: true
  issuer: dummy-issuer
  jwksUri: dummy-jwksuri
  audiences: []
  forwardOriginalToken: true
  outputPayloadToHeader: "jwt-base-64"
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to:
        - operation:
            methods: ['GET']
            paths: ["/", "/*", "/slug/*"]
